// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/resources/commodities": {
    params: {};
  };
  "/resources/latest": {
    params: {};
  };
  "/resources/series": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/history": {
    params: {};
  };
  "/markets": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/resources/commodities" | "/resources/latest" | "/resources/series" | "/settings" | "/history" | "/markets";
  };
  "routes/resources.commodities.tsx": {
    id: "routes/resources.commodities";
    page: "/resources/commodities";
  };
  "routes/resources.latest.tsx": {
    id: "routes/resources.latest";
    page: "/resources/latest";
  };
  "routes/resources.series.tsx": {
    id: "routes/resources.series";
    page: "/resources/series";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/settings" | "/history" | "/markets" | "/";
  };
  "routes/_layout.settings.tsx": {
    id: "routes/_layout.settings";
    page: "/settings";
  };
  "routes/_layout.history.tsx": {
    id: "routes/_layout.history";
    page: "/history";
  };
  "routes/_layout.markets.tsx": {
    id: "routes/_layout.markets";
    page: "/markets";
  };
  "routes/_layout._index.tsx": {
    id: "routes/_layout._index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/resources.commodities": typeof import("./app/routes/resources.commodities.tsx");
  "routes/resources.latest": typeof import("./app/routes/resources.latest.tsx");
  "routes/resources.series": typeof import("./app/routes/resources.series.tsx");
  "routes/_layout": typeof import("./app/routes/_layout.tsx");
  "routes/_layout.settings": typeof import("./app/routes/_layout.settings.tsx");
  "routes/_layout.history": typeof import("./app/routes/_layout.history.tsx");
  "routes/_layout.markets": typeof import("./app/routes/_layout.markets.tsx");
  "routes/_layout._index": typeof import("./app/routes/_layout._index.tsx");
};