// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/history": {
    params: {};
  };
  "/markets": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/settings" | "/history" | "/markets";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/settings" | "/history" | "/markets" | "/";
  };
  "routes/_layout.settings.tsx": {
    id: "routes/_layout.settings";
    page: "/settings";
  };
  "routes/_layout.history.tsx": {
    id: "routes/_layout.history";
    page: "/history";
  };
  "routes/_layout.markets.tsx": {
    id: "routes/_layout.markets";
    page: "/markets";
  };
  "routes/_layout._index.tsx": {
    id: "routes/_layout._index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_layout": typeof import("./app/routes/_layout.tsx");
  "routes/_layout.settings": typeof import("./app/routes/_layout.settings.tsx");
  "routes/_layout.history": typeof import("./app/routes/_layout.history.tsx");
  "routes/_layout.markets": typeof import("./app/routes/_layout.markets.tsx");
  "routes/_layout._index": typeof import("./app/routes/_layout._index.tsx");
};